### ISSUE TITLE
[ Problem ] Dark Mode

### ISSUE THREAD

**Issue by xuwillie** [nikolovlazar/nikolovlazar.com#13]
ayyyy, nice to meet u!

I met a problem about your website. If I selected dark mode, and reflash page, then it will restore to light mode.

**Comment by nikolovlazar** [comment]
The theme reflects on the device's Dark Mode / Light Mode setting. Try changing your device to Dark Mode, and the initial color will always be dark. I wanted to make it simple and just follow the device, therefore setting it to Dark and refreshing it will always come back to Light if you device is set to Light Mode.
