### ISSUE TITLE
Search would not show posts if query is typed in all lowercase

### ISSUE THREAD

**Issue by c-khenzy** [nikolovlazar/nikolovlazar.com#9]
Would have done the the `search-query` on `/pages/blog/index.tsx` differently since it will not show any posts if you type the title all in lowercase.
```jsx
const filteredPosts = posts.filter((post) =>
  post.title.toLowerCase().includes(query.toLowerCase())
);
setDisplayPosts(filteredPosts);
```

Anyways beautiful site 😀

**Comment by nikolovlazar** [comment]
You're absolutely right @c-khenzy! I'll push a fix for that. Thanks a bunch ❤️
